---
- name: Configure NGINX with Local or Remote Config
  hosts: web_servers
  become: yes
  vars:
    use_remote_config: false  # Set to false to use a local file
    nginx_local_path: "./nginx.conf"
    nginx_remote_url: "https://raw.githubusercontent.com/nginx/nginx/master/conf/nginx.conf"
    nginx_dest: "/etc/nginx/nginx.conf"

  tasks:
    - name: Use local NGINX config
      copy:
        src: "{{ nginx_local_path }}"
        dest: "{{ nginx_dest }}"
        owner: root
        group: root
        mode: '0644'
      when: not use_remote_config
      notify: Reload NGINX

    - name: Fetch remote NGINX config
      get_url:
        url: "{{ nginx_remote_url }}"
        dest: "{{ nginx_dest }}"
        owner: root
        group: root
        mode: '0644'
      register: download_result
      ignore_errors: yes
      when: use_remote_config
      notify: Reload NGINX

    - name: Fail if download unsuccessful
      fail:
        msg: "Failed to download NGINX config from {{ nginx_remote_url }}"
      when: download_result.failed is defined and download_result.failed

  handlers:
    - name: Reload NGINX
      service:
        name: nginx
        state: reloaded
